
insert into LOCATION values (1,'BELFORT');

insert into LOCATION values (2,'MONTBELIARD');

insert into LOCATION values (3,'SEVENANS');

insert into COURSE
values ('BD50','Design of databases','Acquisition of skills on methods and databases design tools and data models.','BD50.png');

insert into COURSE
values ('EI04','Industrial Buying, Selling and Negotiation','The course presents an introduction to buying, selling and negotiation providing students with practice and experience of techniques.','EI04.png');

insert into COURSE
values ('GL52','Software engineering','The skills on methodologies, languages and software development environments : Life Cycle and Agile ( SCRUM ) , functional approaches , methods of analysis and object oriented design, formal specifications , pattern design.','GL52.png');

insert into COURSE
values ('LG00','German real beginner','Introduction to German Communication in situations of everyday life gradually integrating basic grammar.','LG00.png');
  
insert into COURSE
values ('LO54','Java Enterprise Applications Architectures and Development Frameworks','Skills on the design and implementation of a Java Web Application operating with persistent data.','LO54.png');

insert into COURSE
values ('MI44','Computer Security','Introduction to Computer Security, methods of analysis and improvement of information systems security.','MI44.png');
  
insert into COURSE
values ('RE51','Distributed algorithms and protocols','Communication protocols and distributed data management, Modern distributed systems including through the concepts of cloud computing, ubiquitous computing and networks on chips.','RE51.png');
    
insert into COURSE
values ('VI51','Artificial Intelligence for Games and Virtual Environments','Acquire the skills on the concepts and the tools required to create virtual simulations with and without interactions with the end-user. The focus is on the simulation models instead of the geometrical and graphical models.','VI51.png');

1 row created.


insert into COURSE_SESSION
values (1,1,'BD50','01/05/16','15/05/16');
  
insert into COURSE_SESSION
values (2,2,'BD50','16/05/16','30/05/16');  

insert into COURSE_SESSION
values (3,3,'BD50','01/06/16','15/06/16');  

insert into COURSE_SESSION
values (4,1,'BD50','16/06/16','30/06/16');  
  
insert into COURSE_SESSION
values (5,3,'BD50','01/07/16','15/07/16');
  
  
insert into COURSE_SESSION
values (6,1,'GL52','01/05/16','15/05/16');

insert into COURSE_SESSION
values (7,2,'GL52','01/06/16','15/06/16');  
  
insert into COURSE_SESSION
values (8,3,'GL52','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (9,3,'GL52','01/07/16','15/07/16');   

insert into COURSE_SESSION
values (10,2,'GL52','16/07/16','30/07/16');    

insert into COURSE_SESSION
values (11,1,'GL52','01/08/16','15/08/16'); 

  
insert into COURSE_SESSION
values (12,2,'EI04','01/05/16','15/05/16');  

insert into COURSE_SESSION
values (13,3,'EI04','16/05/16','30/05/16'); 

insert into COURSE_SESSION
values (14,1,'EI04','01/06/16','15/06/16');   

insert into COURSE_SESSION
values (15,2,'EI04','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (16,2,'EI04','01/07/16','15/07/16'); 


insert into COURSE_SESSION
values (17,1,'LG00','01/05/16','15/05/16');

insert into COURSE_SESSION
values (18,2,'LG00','01/06/16','15/06/16');  
  
insert into COURSE_SESSION
values (19,3,'LG00','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (20,3,'LG00','01/07/16','15/07/16');   

insert into COURSE_SESSION
values (21,2,'LG00','16/07/16','30/07/16');    

insert into COURSE_SESSION
values (22,1,'LG00','01/08/16','15/08/16'); 


insert into COURSE_SESSION
values (23,1,'LO54','01/05/16','15/05/16');  

insert into COURSE_SESSION
values (24,3,'LO54','16/05/16','30/05/16'); 

insert into COURSE_SESSION
values (25,1,'LO54','01/06/16','15/06/16');   

insert into COURSE_SESSION
values (26,2,'LO54','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (27,2,'LO54','01/07/16','15/07/16'); 
  

insert into COURSE_SESSION
values (28,1,'MI44','01/05/16','15/05/16');   

insert into COURSE_SESSION
values (29,2,'MI44','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (30,2,'MI44','01/07/16','15/07/16');   
  

insert into COURSE_SESSION
values (31,3,'RE51','01/05/16','15/05/16');

insert into COURSE_SESSION
values (32,2,'RE51','01/06/16','15/06/16');  
  
insert into COURSE_SESSION
values (33,3,'RE51','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (34,3,'RE51','01/07/16','15/07/16');   

insert into COURSE_SESSION
values (35,2,'RE51','16/07/16','30/07/16');    

insert into COURSE_SESSION
values (36,1,'RE51','01/08/16','15/08/16'); 
  

insert into COURSE_SESSION
values (37,1,'VI51','01/05/16','15/05/16');  

insert into COURSE_SESSION
values (38,3,'VI51','16/05/16','30/05/16'); 

insert into COURSE_SESSION
values (39,1,'VI51','01/06/16','15/06/16');   

insert into COURSE_SESSION
values (40,2,'VI51','16/06/16','30/06/16'); 

insert into COURSE_SESSION
values (41,3,'VI51','01/07/16','15/07/16'); 